import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { wrapper } from '@/state/store';
import {
  getPokemon,
  getPokemons,
  getRunningQueriesThunk,
} from '@/state/slices/pokemonsApi';
import { IPokemon, IPokemonsResponse } from '@/types';
import PokemonCard from '@/components/Pokemon/PokemonCard/PokemonCard';

const inter = Inter({ subsets: ['latin'] });

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    const limit = 4;
    const offset = 0;
    const pokemons = await store.dispatch(
      getPokemons.initiate({ limit, offset })
    );

    const pokemonsFullInfo: IPokemon[] = [];
    pokemons.data?.results.map(async (pokemon) => {
      const singlePokemon = await store.dispatch(
        getPokemon.initiate(pokemon.name)
      );
      const singlePokemonData = singlePokemon.data;
      if (singlePokemonData) {
        pokemonsFullInfo.push(singlePokemonData);
      }
    });
    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return {
      props: { pokemons, pokemonsFullInfo },
    };
  }
);

export default function Home({
  pokemons,
  pokemonsFullInfo,
}: {
  pokemons: IPokemonsResponse;
  pokemonsFullInfo: IPokemon[];
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="pokemon">
          <ul className="pokemon__list">
            <PokemonCard pokemonsFullInfo={pokemonsFullInfo}></PokemonCard>
          </ul>
        </div>
      </main>
    </>
  );
}
